import React, { createContext, useContext, useEffect, useMemo, useState } from "react";
import { updateProfile as updateProfileAPI } from "../api/authAPI.js";

const KEY = "lang";

const STRINGS = {
  en: {
    appName: "ETHIOPIAN IMPORT\nMANAGEMENT SYSTEM",
    home: "Home",
    declare: "Declare",
    assistant: "Assistant",
    logout: "Logout",
    analytics: "Analytics",
    economicOperators: "Economic Operators",
    shipmentDesk: "Shipment Desk",
    declarationDesk: "Declaration Desk",
    declarationAdmin: "Declaration Admin",
    inspectionDesk: "Inspection Desk",
    paymentBoard: "Payment Board",
    financeWorkspace: "Finance Workspace",
    trackingCenter: "Tracking Center",
    deviceRegistry: "Device Registry",
    locations: "Locations",
    singleWindow: "Single Window",
    smartAnalytics: "Smart Analytics",
    dataHealth: "Data Health",
    myTracking: "My Tracking",
    clearanceControl: "Clearance Control",
    performance: "Performance",
    dataAnalysis: "Data Analysis",
    users: "Users",
    activeUsers: "Active Users",
    aboutUser: "About User",
    aboutUserText: "Manage user accounts, assign roles, activate or deactivate access, and reset passwords for secure customs operations.",
    notificationsAdmin: "Notifications Admin",
    reports: "Reports",
    fileUpload: "File Upload",
    profile: "Profile",
    language: "Language",
    menu: "Menu",
    english: "English",
    amharic: "Amharic",
    signIn: "Sign in",
    signingIn: "Signing in...",
    welcomeBack: "Welcome Back",
    secureAccess: "Secure access to dashboards, declarations, and tracking.",
    customsOperationsPortal: "Ethiopian Import Management System",
    signInPrompt: "Sign in to your customs account.",
    checkingService: "Checking service",
    serviceOnline: "Service online",
    serviceOffline: "Service unavailable",
    retry: "Retry",
    show: "Show",
    hide: "Hide",
    authorizedAccessOnly: "Authorized access only. Sign-in activity is monitored.",
    email: "Email",
    password: "Password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    forgotPasswordTitle: "Forgot password",
    forgotPasswordHint: "Enter your email and we'll send reset instructions (stub).",
    cancel: "Cancel",
    sendResetLink: "Send reset link",
    emailRequired: "Email required",
    resetInstructionsSent: "If this account exists, reset instructions were sent.",
    resetFailed: "Reset failed (endpoint may be unavailable)",
    loginFailed: "Login failed",
    homeHero: "Home",
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    homeSubtitle: "Operational shortcuts and exports in one place",
    dashboardPdf: "Dashboard PDF",
    declarationsCsv: "Declarations CSV",
    devicesCsv: "Devices CSV",
    locationsCsv: "Locations CSV",
    recentDeclarations: "Recent Declarations",
    pending: "Pending",
    recentShipments: "Recent Shipments",
    inTransit: "In Transit",
    roleWorkspace: "Role Workspace",
    unknown: "Unknown",
    modules: "Modules",
    recentDeclarationsLower: "Recent declarations",
    reload: "Reload",
    noRecentDeclarations: "No recent declarations",
    noShipmentsYet: "No shipments yet",
    failedToLoadShipments: "Failed to load shipments",
    analyticsDesc: "Live dashboards and KPIs",
    declarationDeskDesc: "Create and manage declarations",
    trackingCenterDesc: "Live shipment movement and route visibility",
    myTrackingDesc: "Importer self-service timeline and live map",
    deviceRegistryDesc: "GPS device control and assignment",
    smartAnalyticsDesc: "Revenue, risk, clearance, forecasts, and drill-down intelligence",
    dataHealthDesc: "Integrity diagnostics, duplicate review plans, and index readiness",
    dataHealthHealthy: "All monitored integrity protections are healthy.",
    dataHealthReviewRequired: "Integrity issues require Admin review.",
    dataHealthUnavailable: "Data Health status unavailable",
    duplicateGroups: "duplicate groups",
    blockedIndexes: "blocked indexes",
    missingIndexes: "missing indexes",
    reviewDataHealth: "Review Data Health",
    refreshStatus: "Refresh status",
    lastChecked: "Last checked",
    reportsDesc: "Exports and audit-ready reports",
    settings: "Settings",
    settingsSaved: "Settings saved",
    apiBase: "API Base",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    displayPreset: "Display Preset",
    comfortableLight: "Comfortable Light",
    comfortableDark: "Comfortable Dark",
    compactLight: "Compact Light",
    compactDark: "Compact Dark",
    tableDensity: "Table Density",
    comfortable: "Comfortable",
    compact: "Compact",
    compactHint: "Compact reduces table row padding for higher information density.",
    pageSize: "Page Size",
    showActionToasts: "Show action toasts (palette and navbar toggles)",
    save: "Save",
    saving: "Saving...",
    fullName: "Full Name",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    savedSuccessfully: "Saved successfully",
    saveFailed: "Save failed",
    passwordMismatch: "New password and confirmation do not match",
    currentPasswordRequired: "Current password is required to change password",
    notifications: "Notifications",
    markAllRead: "Mark all read",
    loading: "Loading...",
    noNotifications: "No notifications",
    appLegal: "All rights reserved.",
    headOffice: "Head Office",
    officeHours: "Office hours",
    privacy: "Privacy",
    terms: "Terms",
    contact: "Contact",
    menuLabel: "Menu",
    searchPagesHint: "Search pages... (Ctrl/Cmd+K)",
    commandNoMatches: "No matches. Try another keyword.",
    commandTip: "Tip: Use arrows to navigate, Enter to open, Esc to close. Type \"Toggle Density\" to switch compact mode.",
    action: "Action",
    page: "Page",
    unauthorized: "Unauthorized",
    noAccessPage: "You do not have access to this page.",
    failedToLoadAnalytics: "Failed to load analytics",
    customsAnalyticsTitle: "Customs Analytics Control Center",
    customsAnalyticsSubtitle: "Live customs performance, risk distribution, and revenue monitoring",
    exporting: "Exporting...",
    exports: "Exports",
    exportAllCsv: "Export all CSVs",
    revenueCsv: "Revenue CSV",
    riskCsv: "Risk CSV",
    sectorCsv: "Sector CSV",
    countriesCsv: "Countries CSV",
    clearanceAvgCsv: "Clearance Avg CSV",
    pendingVsClearedCsv: "Pending vs Cleared CSV",
    allExportsReady: "All exports ready",
    exportAllFailed: "Export all failed",
    exportReady: "Export ready",
    csvDownloadFailed: "CSV download failed",
    failedToLoadAnalyticsPrefix: "Failed to load analytics:",
    totalRevenue: "Total Revenue",
    greenChannelPercent: "Green Channel %",
    yellowChannelPercent: "Yellow Channel %",
    redChannelPercent: "Red Channel %",
    clearanceRate: "Clearance Rate",
    avgClearanceTime: "Avg Clearance Time",
    allDutiesVatExcise: "All duties, VAT, excise",
    lowRiskShare: "Low-risk share",
    mediumRiskShare: "Medium-risk share",
    highRiskShare: "High-risk share",
    clearedOverTotal: "Cleared / total",
    acrossActivePorts: "Across active ports",
    queueCoverage: "Queue Coverage",
    totalDeclsInRiskQueues: "Total declarations in risk queues",
    topRiskImporter: "Top Risk Importer",
    topRiskHs: "Top Risk HS",
    topRiskCountry: "Top Risk Country",
    taxRevenueTrends: "Tax Revenue Trends",
    riskChannelDistribution: "Risk Channel Distribution",
    pendingVsCleared: "Pending vs. Cleared",
    avgClearanceByPort: "Avg Clearance Time (days) by Port",
    importVolumeBySector: "Import Volume by Sector",
    topTradingCountries: "Top Trading Countries",
    country: "Country",
    shipments: "Shipments",
    noCountryData: "No country data",
    forecastRevenue: "Forecast: Revenue (next 3 months)",
    operationalRiskQueues: "Operational Risk Queues",
    highRisk: "High Risk",
    mediumRisk: "Medium Risk",
    lowRisk: "Low Risk",
    declaration: "Declaration",
    importer: "Importer",
    risk: "Risk",
    score: "Score",
    noHighRiskDecls: "No high-risk declarations",
    noMediumRiskDecls: "No medium-risk declarations",
    noLowRiskDecls: "No low-risk declarations",
    riskIntelligenceAdmin: "Risk Intelligence (Admin)",
    highRiskHsCodes: "High-risk HS codes",
    redDecls: "Red Decls",
    avgRisk: "Avg Risk",
    noHighRiskHsData: "No high-risk HS data",
    topRiskyImporters: "Top risky importers",
    red: "Red",
    noRiskyImporterData: "No risky importer data",
    countryRiskHeatmapTable: "Country risk heatmap (table)",
    noCountryRiskData: "No country risk data",
    future: "Future",
    upcomingCustomsFlows: "Upcoming Customs Flows (Preview)",
    futurePreviewBody: "Toggle roles, simulate tariff tweaks, and preview UI changes without touching production data.",
    launchPreview: "Launch Preview",
    roleSwap: "Role swap",
    draftDuties: "Draft duties",
    uiPreview: "UI preview",
    topImportedGoods: "Top Imported Goods (by CIF)",
    couldNotLoadGoodsData: "Could not load goods data.",
    hsCode: "HS Code",
    description: "Description",
    totalCifUsd: "Total CIF (USD)",
    declarations: "Declarations",
    noGoodsData: "No goods data",
    couldNotLoadRevenueData: "Could not load revenue data.",
    couldNotLoadRiskData: "Could not load risk data.",
    couldNotLoadCounts: "Could not load counts.",
    couldNotLoadClearanceAverages: "Could not load clearance averages.",
    couldNotLoadSectorData: "Could not load sector data.",
    couldNotLoadCountryData: "Could not load country data.",
    couldNotLoadForecast: "Could not load forecast.",
    paymentControlBoard: "Payment Control Board",
    financeWorkflowSubtitle: "Finance workflow for collection, verification, and approval",
    assessedAmount: "Assessed Amount",
    outstandingAmount: "Outstanding Amount",
    pendingAmount: "Pending Amount",
    verifiedAmount: "Verified Amount",
    paidPayments: "Paid Payments",
    pendingReview: "Pending Review",
    readyForApproval: "Ready for Approval",
    failedPayments: "Failed Payments",
    financeSummaryUnavailable: "Finance summary unavailable",
    declarationSubmittedPendingPayment: "Declaration submitted. A pending payment record has been created.",
    dismiss: "Dismiss",
    paymentQueue: "Payment Queue",
    noPaymentRecords: "No payment records found.",
    selectPaymentFromQueue: "Select a payment from the queue.",
    totalPayable: "Total Payable",
    paymentMethod: "Payment Method",
    orderNumber: "Order Number",
    receiptNumber: "Receipt Number",
    workflowTimeline: "Workflow Timeline",
    paymentCreated: "Payment Created",
    paymentInitiated: "Payment Initiated",
    verified: "Verified",
    approvedPaid: "Approved / Paid",
    done: "Done",
    pendingWord: "Pending",
    initiatePayment: "Initiate Payment",
    processing: "Processing...",
    markVerified: "Mark Verified",
    approvePayment: "Approve Payment",
    retryPayment: "Retry Payment",
    downloadReceipt: "Download Receipt",
    paymentInitiatedToast: "payment initiated.",
    paymentCompletedApproved: "Payment completed and approved.",
    paymentVerified: "Payment verified.",
    paymentApproved: "Payment approved.",
    paymentResetPending: "Payment reset to Pending.",
    failedToLoadPayments: "Failed to load payments",
    paymentInitiationFailed: "Payment initiation failed",
    verificationFailed: "Verification failed",
    approvalFailed: "Approval failed",
    retryFailed: "Retry failed",
    failedToDownloadReceipt: "Failed to download receipt",
    reportsTitle: "Reports",
    reportType: "Report Type",
    dateWindow: "Date Window",
    format: "Format",
    previewRows: "Preview Rows",
    any: "Any",
    declarationsType: "declarations",
    shipmentsType: "shipments",
    paymentsType: "payments",
    inspectionsType: "inspections",
    clearancesType: "clearances",
    performanceType: "performance",
    paymentStatus: "Payment Status",
    all: "All",
    dateFrom: "Date From",
    dateTo: "Date To",
    importerIdOptional: "Importer ID (optional)",
    importerIdPlaceholder: "UUID of importer",
    importerFilterNote: "Importer filter applies to Shipments and Performance only.",
    excel: "Excel",
    generating: "Generating...",
    generate: "Generate",
    failedToGenerateReport: "Failed to generate report",
    unsupportedReportType: "Unsupported report type",
    preview: "Preview",
    live: "Live",
    connecting: "Connecting",
    disconnected: "Disconnected",
    idle: "Idle",
    trackingOperationsCenter: "Tracking Operations Center",
    trackingOpsSubtitle: "Live movement visibility, destination proximity, and ETA monitoring",
    shipmentQueue: "Shipment Queue",
    searchReferenceTrackingImporter: "Search reference / tracking / importer",
    loadingShipments: "Loading shipments...",
    noDestination: "No destination",
    noShipmentsFound: "No shipments found.",
    selectShipmentLiveTracking: "Select a shipment to view live tracking.",
    trackingReference: "Tracking Reference",
    lastUpdate: "Last update",
    noStreamEventYet: "No stream event yet",
    reconnect: "Reconnect",
    currentCoordinates: "Current Coordinates",
    speed: "Speed",
    destination: "Destination",
    distanceToDestination: "Distance to Destination",
    estimatedArrival: "Estimated Arrival",
    fitRoute: "Fit Route",
    refreshRegistry: "Refresh Registry",
    failedToLoadTrackingRegistry: "Failed to load tracking registry",
    failedToLoadShipmentTracking: "Failed to load shipment tracking",
    myShipmentTracking: "My Shipment Tracking",
    importerViewSubtitle: "Importer view for declaration progress and live shipment movement",
    searchShipment: "Search Shipment",
    searchShipmentHelp: "Use declaration number, shipment reference, BL, AWB, or container number.",
    searchPlaceholder: "DEC-ET-2026-00001 / SHP-... / BL...",
    searching: "Searching...",
    search: "Search",
    noShipmentSelectedHint: "No shipment selected. Run a search to load your timeline and live map.",
    shipmentSummary: "Shipment Summary",
    declarationNo: "Declaration No",
    shipmentRef: "Shipment Ref",
    coordinates: "Coordinates",
    openFullTracking: "Open Full Tracking",
    openPayments: "Open Payments",
    downloadReleaseDocs: "Download Release PDF",
    downloadReleaseDocsTitle: "Download release PDF",
    completeRequirementsToDownload: "Complete all requirements to enable download",
    releaseDocsUnavailable: "Release docs unavailable. Missing:",
    paymentConfirmation: "payment confirmation;",
    inspectionReq: "inspection;",
    clearanceReq: "clearance;",
    documentsReq: "documents",
    statusTimeline: "Status Timeline",
    date: "Date",
    liveMap: "Live Map",
    enterTrackingSearch: "Enter declaration, tracking, BL, or container number",
    searchFailed: "Search failed",
    declarationNotFoundForShipment: "Declaration not found for this shipment",
    releaseDocsDownloaded: "Release PDF downloaded",
    releaseDocsNotReady: "Release documents are not ready yet",
    declarationProcessing: "Declaration Processing",
    euStyleDeclarationWorkflow: "EU-style declaration workflow with review actions",
    newDeclaration: "New Declaration",
    selectShipmentAndCompleteDeclaration: "Select a shipment and complete customs declaration metadata.",
    shipment: "Shipment",
    selectShipment: "Select shipment...",
    allShipmentsAlreadyDeclared: "All shipments already have declarations.",
    declarationNumber: "Declaration Number",
    autoIfEmpty: "Auto if empty",
    auto: "Auto",
    declarationDate: "Declaration Date",
    declarantAgent: "Declarant Agent",
    customsStation: "Customs Station",
    valuationBasis: "Valuation Basis",
    currency: "Currency",
    tariffRatePercent: "Tariff Rate (%)",
    selectRate: "Select rate...",
    custom: "Custom",
    customTariffPercent: "Custom Tariff (%)",
    dutiesEtb: "Duties (ETB)",
    optionalManualAmount: "Optional manual amount",
    paymentReceiptNumber: "Payment Receipt Number",
    estimatedPreview: "Estimated Preview",
    cifValueUsd: "CIF Value (USD)",
    exchangeRate: "Exchange Rate",
    estimatedDutyEtb: "Estimated Duty (ETB)",
    addShipment: "Add Declaration",
    addDeclaration: "Add Declaration",
    submitting: "Submitting...",
    submitDeclaration: "Submit Declaration",
    declarationsRegistry: "Declarations Registry",
    filterByDeclarationId: "Filter by declaration_id",
    clear: "Clear",
    dateShort: "Date",
    tariffPercent: "Tariff %",
    actions: "Actions",
    status: "Status",
    documents: "Documents",
    upload: "Upload",
    approve: "Approve",
    reject: "Reject",
    rejectionReasonOptional: "Rejection reason (optional)",
    noDeclarationRecordsFound: "No declaration records found.",
    declarationDocuments: "Declaration Documents",
    uploadManagedInFileUpload: "Upload workflow is managed in the File Upload page.",
    goToFileUpload: "Go to File Upload",
    noDocumentsForDeclaration: "No documents for this declaration.",
    documentPreview: "Document Preview",
    selectDocumentToPreview: "Select a document to preview.",
    loadingDocument: "Loading document...",
    openNewTab: "Open in new tab",
    uploaded: "Uploaded",
    open: "Open",
    delete: "Delete",
    deleteThisDocument: "Delete this document?",
    documentDeleted: "Document deleted",
    deleteFailed: "Delete failed",
    previewing: "Previewing...",
    previewFailed: "Preview failed",
    ocrPreview: "OCR Preview",
    pleaseSelectShipment: "Please select a shipment.",
    pleaseCompleteRequiredFields: "Please complete the required fields.",
    tariffRateRequired: "Tariff rate is required.",
    invalidNumber: "Enter a valid number.",
    declarationSubmittedSuccessfully: "Declaration submitted successfully.",
    failedToSubmitDeclaration: "Failed to submit declaration",
    failedToLoadDeclarations: "Failed to load declarations",
    failedToLoadDocuments: "Failed to load documents",
    declarationApproved: "Declaration approved",
    approveFailed: "Approve failed",
    declarationRejected: "Declaration rejected",
    rejectFailed: "Reject failed",
  },
  am: {
    appName: "ETHIOPIAN IMPORT\nMANAGEMENT SYSTEM",
    home: "መነሻ",
    declare: "አሳውቅ",
    search: "ፍለጋ",
    assistant: "አጋዥ",
    logout: "ውጣ",
    analytics: "ትንታኔ",
    economicOperators: "ኢኮኖሚክ ኦፕሬተሮች",
    shipmentDesk: "የጭነት ዴስክ",
    declarationDesk: "የመግለጫ ዴስክ",
    declarationAdmin: "የመግለጫ አስተዳደር",
    inspectionDesk: "የምርመራ ዴስክ",
    paymentBoard: "የክፍያ ቦርድ",
    financeWorkspace: "የፋይናንስ የስራ ቦታ",
    trackingCenter: "የክትትል ማዕከል",
    deviceRegistry: "የመሳሪያ መዝገብ",
    locations: "ቦታዎች",
    singleWindow: "ነጠላ መስኮት",
    smartAnalytics: "Smart Analytics",
    dataHealth: "Data Health",
    myTracking: "የእኔ ክትትል",
    clearanceControl: "የክሊራንስ ቁጥጥር",
    performance: "አፈጻጸም",
    dataAnalysis: "የውሂብ ትንታኔ",
    users: "ተጠቃሚዎች",
    activeUsers: "ንቁ ተጠቃሚዎች",
    aboutUser: "ስለ ተጠቃሚ",
    aboutUserText: "ለደህንነት የጉምሩክ ሥራዎች ተጠቃሚ መለያዎችን ያስተዳድሩ፣ ሚና ይመድቡ፣ መዳረሻ ያንቁ/ያጥፉ እና የይለፍ ቃል ዳግም ያዘጋጁ።",
    notificationsAdmin: "የማሳወቂያ አስተዳደር",
    reports: "ሪፖርቶች",
    fileUpload: "ፋይል መጫን",
    profile: "መገለጫ",
    language: "ቋንቋ",
    menu: "ሜኑ",
    english: "እንግሊዝኛ",
    amharic: "አማርኛ",
    signIn: "ግባ",
    signingIn: "በመግባት ላይ...",
    welcomeBack: "እንኳን ደህና መጡ",
    secureAccess: "ወደ ዳሽቦርዶች፣ መግለጫዎች እና ክትትል የተጠበቀ መዳረሻ።",
    customsOperationsPortal: "Ethiopian Import Management System",
    signInPrompt: "ወደ የጉምሩክ መለያዎ ይግቡ።",
    checkingService: "Checking service",
    serviceOnline: "Service online",
    serviceOffline: "Service unavailable",
    retry: "Retry",
    show: "Show",
    hide: "Hide",
    authorizedAccessOnly: "Authorized access only. Sign-in activity is monitored.",
    email: "ኢሜይል",
    password: "የይለፍ ቃል",
    rememberMe: "አስታውሰኝ",
    forgotPassword: "የይለፍ ቃል ረሱ?",
    forgotPasswordTitle: "የይለፍ ቃል ረሱ",
    forgotPasswordHint: "ኢሜይልዎን ያስገቡ፤ የመቀየሪያ መመሪያ እንልካለን።",
    cancel: "ሰርዝ",
    sendResetLink: "የመቀየሪያ ሊንክ ላክ",
    emailRequired: "ኢሜይል ያስፈልጋል",
    resetInstructionsSent: "ይህ መለያ ካለ የመቀየሪያ መመሪያ ተልኳል።",
    resetFailed: "መቀየር አልተሳካም",
    loginFailed: "መግባት አልተሳካም",
    homeHero: "መነሻ",
    goodMorning: "እንደምን አደሩ",
    goodAfternoon: "እንደምን ዋሉ",
    goodEvening: "እንደምን አመሹ",
    homeSubtitle: "የስራ አቋራጮች እና ኤክስፖርቶች በአንድ ቦታ",
    dashboardPdf: "ዳሽቦርድ PDF",
    declarationsCsv: "መግለጫ CSV",
    devicesCsv: "መሳሪያ CSV",
    locationsCsv: "ቦታዎች CSV",
    recentDeclarations: "የቅርብ ጊዜ መግለጫዎች",
    pending: "በመጠባበቅ ላይ",
    recentShipments: "የቅርብ ጊዜ ጭነቶች",
    inTransit: "በመጓጓዣ ላይ",
    roleWorkspace: "የሚና የስራ ቦታ",
    unknown: "ያልታወቀ",
    modules: "ሞጁሎች",
    open: "ክፈት",
    recentDeclarationsLower: "የቅርብ ጊዜ መግለጫዎች",
    reload: "እንደገና ጫን",
    noRecentDeclarations: "የቅርብ ጊዜ መግለጫ የለም",
    noShipmentsYet: "ጭነት ገና የለም",
    failedToLoadDeclarations: "መግለጫዎችን መጫን አልተሳካም",
    failedToLoadShipments: "ጭነቶችን መጫን አልተሳካም",
    analyticsDesc: "ቀጥታ ዳሽቦርዶች እና KPI",
    declarationDeskDesc: "መግለጫዎችን ፍጠር እና አስተዳድር",
    trackingCenterDesc: "የጭነት እንቅስቃሴ እና መንገድ ታይነት",
    myTrackingDesc: "የአስመጪ ራስ-አገልግሎት ጊዜ መስመር እና ቀጥታ ካርታ",
    deviceRegistryDesc: "የGPS መሳሪያ ቁጥጥር እና መመደብ",
    smartAnalyticsDesc: "የገቢ፣ ስጋት፣ ክሊራንስ፣ ትንበያ እና ዝርዝር ትንታኔ",
    reportsDesc: "ኤክስፖርቶች እና ለኦዲት ዝግጁ ሪፖርቶች",
    dataHealthDesc: "Integrity diagnostics, duplicate review plans, and index readiness",
    dataHealthHealthy: "All monitored integrity protections are healthy.",
    dataHealthReviewRequired: "Integrity issues require Admin review.",
    dataHealthUnavailable: "Data Health status unavailable",
    duplicateGroups: "duplicate groups",
    blockedIndexes: "blocked indexes",
    missingIndexes: "missing indexes",
    reviewDataHealth: "Review Data Health",
    refreshStatus: "Refresh status",
    lastChecked: "Last checked",
    settings: "ቅንብሮች",
    settingsSaved: "ቅንብሮች ተቀምጠዋል",
    apiBase: "API መሰረት",
    theme: "ገጽታ",
    light: "ብርሃን",
    dark: "ጨለማ",
    displayPreset: "የማሳያ ቅድመ-ቅንብር",
    comfortableLight: "ምቹ ብርሃን",
    comfortableDark: "ምቹ ጨለማ",
    compactLight: "ጥቅል ብርሃን",
    compactDark: "ጥቅል ጨለማ",
    tableDensity: "የሰንጠረዥ ጥግግት",
    comfortable: "ምቹ",
    compact: "ጥቅል",
    compactHint: "ጥቅል ሁኔታ የሰንጠረዥ ረድፍ ክፍተትን ይቀንሳል።",
    pageSize: "የገጽ መጠን",
    showActionToasts: "የተግባር ማሳወቂያዎችን አሳይ",
    save: "አስቀምጥ",
    saving: "በማስቀመጥ ላይ...",
    fullName: "ሙሉ ስም",
    currentPassword: "የአሁኑ የይለፍ ቃል",
    newPassword: "አዲስ የይለፍ ቃል",
    confirmPassword: "የይለፍ ቃል አረጋግጥ",
    savedSuccessfully: "በተሳካ ሁኔታ ተቀምጧል",
    saveFailed: "ማስቀመጥ አልተሳካም",
    passwordMismatch: "አዲስ የይለፍ ቃል እና ማረጋገጫ አይመሳሰሉም",
    currentPasswordRequired: "የይለፍ ቃል ለመቀየር የአሁኑ የይለፍ ቃል ያስፈልጋል",
    notifications: "ማሳወቂያዎች",
    markAllRead: "ሁሉንም የተነበበ ምልክት አድርግ",
    loading: "በመጫን ላይ...",
    noNotifications: "ማሳወቂያ የለም",
    appLegal: "ሁሉም መብቶች የተጠበቁ ናቸው።",
    headOffice: "ዋና ቢሮ",
    officeHours: "የስራ ሰዓታት",
    privacy: "ግላዊነት",
    terms: "ውሎች",
    contact: "አድራሻ",
    menuLabel: "ሜኑ",
    searchPagesHint: "ገጾችን ፈልግ... (Ctrl/Cmd+K)",
    commandNoMatches: "ምንም አልተገኘም። ሌላ ቃል ይሞክሩ።",
    commandTip: "ጠቃሚ ምክር: በአቅጣጫ ቁልፎች ይጓዙ፣ Enter ለመክፈት፣ Esc ለመዝጋት።",
    action: "ተግባር",
    page: "ገጽ",
    unauthorized: "ፍቃድ የለዎትም",
    noAccessPage: "ይህን ገጽ ለመመልከት ፍቃድ የለዎትም።",
    failedToLoadAnalytics: "ትንታኔ መጫን አልተሳካም",
    customsAnalyticsTitle: "የጉምሩክ ትንታኔ መቆጣጠሪያ ማዕከል",
    customsAnalyticsSubtitle: "ቀጥታ የጉምሩክ አፈጻጸም፣ የአደጋ ስርጭት እና የገቢ ክትትል",
    exporting: "በማውጣት ላይ...",
    exports: "ማውጫዎች",
    exportAllCsv: "ሁሉንም CSV አውጣ",
    revenueCsv: "የገቢ CSV",
    riskCsv: "የአደጋ CSV",
    sectorCsv: "የዘርፍ CSV",
    countriesCsv: "የአገሮች CSV",
    clearanceAvgCsv: "የክሊራንስ አማካይ CSV",
    pendingVsClearedCsv: "በመጠባበቅ/የተፈታ CSV",
    allExportsReady: "ሁሉም ማውጫዎች ዝግጁ ናቸው",
    exportAllFailed: "ሁሉንም ማውጣት አልተሳካም",
    exportReady: "ማውጫ ዝግጁ ነው",
    csvDownloadFailed: "CSV ማውረድ አልተሳካም",
    failedToLoadAnalyticsPrefix: "ትንታኔ መጫን አልተሳካም:",
    totalRevenue: "ጠቅላላ ገቢ",
    greenChannelPercent: "አረንጓዴ ቻናል %",
    yellowChannelPercent: "ቢጫ ቻናል %",
    redChannelPercent: "ቀይ ቻናል %",
    clearanceRate: "የክሊራንስ መጠን",
    avgClearanceTime: "አማካይ የክሊራንስ ጊዜ",
    allDutiesVatExcise: "ሁሉም ዲውቲ፣ VAT እና ኤክሳይዝ",
    lowRiskShare: "ዝቅተኛ አደጋ ድርሻ",
    mediumRiskShare: "መካከለኛ አደጋ ድርሻ",
    highRiskShare: "ከፍተኛ አደጋ ድርሻ",
    clearedOverTotal: "የተፈታ / ጠቅላላ",
    acrossActivePorts: "በንቁ ወደቦች",
    queueCoverage: "የተራ ሽፋን",
    totalDeclsInRiskQueues: "በአደጋ ተራዎች ያሉ ጠቅላላ መግለጫዎች",
    topRiskImporter: "ከፍተኛ አደጋ አስመጪ",
    topRiskHs: "ከፍተኛ አደጋ HS",
    topRiskCountry: "ከፍተኛ አደጋ አገር",
    taxRevenueTrends: "የታክስ ገቢ አዝማሚያ",
    riskChannelDistribution: "የአደጋ ቻናል ስርጭት",
    pendingVsCleared: "በመጠባበቅ እና የተፈታ",
    avgClearanceByPort: "አማካይ የክሊራንስ ጊዜ (በወደብ)",
    importVolumeBySector: "የማስመጣት መጠን በዘርፍ",
    topTradingCountries: "ከፍተኛ የንግድ አገሮች",
    country: "አገር",
    shipments: "ጭነቶች",
    noCountryData: "የአገር መረጃ የለም",
    forecastRevenue: "ትንበያ: ገቢ (ቀጣይ 3 ወራት)",
    operationalRiskQueues: "የአሠራር አደጋ ተራዎች",
    highRisk: "ከፍተኛ አደጋ",
    mediumRisk: "መካከለኛ አደጋ",
    lowRisk: "ዝቅተኛ አደጋ",
    declaration: "መግለጫ",
    importer: "አስመጪ",
    risk: "አደጋ",
    score: "ውጤት",
    noHighRiskDecls: "ከፍተኛ አደጋ መግለጫ የለም",
    noMediumRiskDecls: "መካከለኛ አደጋ መግለጫ የለም",
    noLowRiskDecls: "ዝቅተኛ አደጋ መግለጫ የለም",
    riskIntelligenceAdmin: "የአደጋ ብልህነት (አስተዳዳሪ)",
    highRiskHsCodes: "ከፍተኛ አደጋ HS ኮዶች",
    redDecls: "ቀይ መግለጫዎች",
    avgRisk: "አማካይ አደጋ",
    noHighRiskHsData: "ከፍተኛ አደጋ HS መረጃ የለም",
    topRiskyImporters: "ከፍተኛ አደጋ አስመጪዎች",
    red: "ቀይ",
    noRiskyImporterData: "አደገኛ አስመጪ መረጃ የለም",
    countryRiskHeatmapTable: "የአገር አደጋ ሙቀት ካርታ (ሰንጠረዥ)",
    noCountryRiskData: "የአገር አደጋ መረጃ የለም",
    future: "ወደፊት",
    upcomingCustomsFlows: "የሚመጡ የጉምሩክ ሂደቶች (ቅድመ እይታ)",
    futurePreviewBody: "ሚና ቀይር፣ ታሪፍ ለውጥ አስመስል፣ እና UI ለውጦችን ያለ የምርት ውሂብ ይመልከቱ።",
    launchPreview: "ቅድመ እይታ ክፈት",
    roleSwap: "ሚና መቀየር",
    draftDuties: "ረቂቅ ዲውቲዎች",
    uiPreview: "UI ቅድመ እይታ",
    topImportedGoods: "ከፍተኛ የተመጡ እቃዎች (በCIF)",
    couldNotLoadGoodsData: "የእቃ መረጃ መጫን አልተሳካም።",
    hsCode: "HS ኮድ",
    description: "መግለጫ",
    totalCifUsd: "ጠቅላላ CIF (USD)",
    declarations: "መግለጫዎች",
    noGoodsData: "የእቃ መረጃ የለም",
    couldNotLoadRevenueData: "የገቢ መረጃ መጫን አልተሳካም።",
    couldNotLoadRiskData: "የአደጋ መረጃ መጫን አልተሳካም።",
    couldNotLoadCounts: "ቆጠራ መጫን አልተሳካም።",
    couldNotLoadClearanceAverages: "የክሊራንስ አማካዮች መጫን አልተሳካም።",
    couldNotLoadSectorData: "የዘርፍ መረጃ መጫን አልተሳካም።",
    couldNotLoadCountryData: "የአገር መረጃ መጫን አልተሳካም።",
    couldNotLoadForecast: "ትንበያ መጫን አልተሳካም።",
    paymentControlBoard: "የክፍያ መቆጣጠሪያ ቦርድ",
    financeWorkflowSubtitle: "ለመሰብሰብ፣ ለማረጋገጥ እና ለማጽደቅ የፋይናንስ ሂደት",
    declarationSubmittedPendingPayment: "መግለጫ ተልኳል። የተጠባባቂ ክፍያ መዝገብ ተፈጥሯል።",
    dismiss: "ዝጋ",
    paymentQueue: "የክፍያ ተራ",
    noPaymentRecords: "የክፍያ መዝገብ አልተገኘም።",
    selectPaymentFromQueue: "ከተራው ውስጥ ክፍያ ይምረጡ።",
    totalPayable: "ጠቅላላ የሚከፈል",
    paymentMethod: "የክፍያ ዘዴ",
    orderNumber: "የትእዛዝ ቁጥር",
    receiptNumber: "የደረሰኝ ቁጥር",
    workflowTimeline: "የሂደት ጊዜ መስመር",
    paymentCreated: "ክፍያ ተፈጠረ",
    paymentInitiated: "ክፍያ ተጀመረ",
    verified: "ተረጋግጧል",
    approvedPaid: "ጸድቋል / ተከፍሏል",
    done: "ተጠናቋል",
    pendingWord: "በመጠባበቅ ላይ",
    initiatePayment: "ክፍያ ጀምር",
    processing: "በሂደት ላይ...",
    markVerified: "ተረጋግጧል ምልክት አድርግ",
    approvePayment: "ክፍያ አጽድቅ",
    retryPayment: "ክፍያ እንደገና ሞክር",
    downloadReceipt: "ደረሰኝ አውርድ",
    paymentInitiatedToast: "ክፍያ ተጀምሯል።",
    paymentCompletedApproved: "ክፍያ ተጠናቋል እና ጸድቋል።",
    paymentVerified: "ክፍያ ተረጋግጧል።",
    paymentApproved: "ክፍያ ጸድቋል።",
    paymentResetPending: "ክፍያ ወደ ተጠባባቂ ተመልሷል።",
    failedToLoadPayments: "ክፍያዎችን መጫን አልተሳካም",
    paymentInitiationFailed: "ክፍያ መጀመር አልተሳካም",
    verificationFailed: "ማረጋገጥ አልተሳካም",
    approvalFailed: "ማጽደቅ አልተሳካም",
    retryFailed: "እንደገና መሞከር አልተሳካም",
    failedToDownloadReceipt: "ደረሰኝ ማውረድ አልተሳካም",
    reportsTitle: "ሪፖርቶች",
    reportType: "የሪፖርት አይነት",
    dateWindow: "የቀን ክልል",
    format: "ቅርጸት",
    previewRows: "የቅድመ እይታ ረድፎች",
    any: "ማንኛውም",
    declarationsType: "መግለጫዎች",
    shipmentsType: "ጭነቶች",
    paymentsType: "ክፍያዎች",
    inspectionsType: "ምርመራዎች",
    clearancesType: "ክሊራንሶች",
    performanceType: "አፈጻጸም",
    paymentStatus: "የክፍያ ሁኔታ",
    all: "ሁሉም",
    dateFrom: "ከቀን",
    dateTo: "እስከ ቀን",
    importerIdOptional: "የአስመጪ መለያ (አማራጭ)",
    importerIdPlaceholder: "የአስመጪ UUID",
    importerFilterNote: "የአስመጪ ማጣሪያ ለጭነትና አፈጻጸም ብቻ ይሰራል።",
    excel: "ኤክሴል",
    generating: "በመፍጠር ላይ...",
    generate: "ፍጠር",
    failedToGenerateReport: "ሪፖርት መፍጠር አልተሳካም",
    unsupportedReportType: "ያልተደገፈ የሪፖርት አይነት",
    preview: "ቅድመ እይታ",
    live: "ቀጥታ",
    connecting: "በመገናኘት ላይ",
    disconnected: "ተቋርጧል",
    idle: "አቋም ላይ",
    trackingOperationsCenter: "የክትትል ኦፕሬሽን ማዕከል",
    trackingOpsSubtitle: "ቀጥታ እንቅስቃሴ ታይነት፣ የመድረሻ ቅርበት እና ETA ክትትል",
    shipmentQueue: "የጭነት ተራ",
    searchReferenceTrackingImporter: "ማጣቀሻ / ክትትል / አስመጪ ፈልግ",
    loadingShipments: "ጭነቶች በመጫን ላይ...",
    noDestination: "መድረሻ የለም",
    noShipmentsFound: "ጭነት አልተገኘም።",
    selectShipmentLiveTracking: "ቀጥታ ክትትል ለማየት ጭነት ይምረጡ።",
    trackingReference: "የክትትል ማጣቀሻ",
    lastUpdate: "የመጨረሻ ማዘመኛ",
    noStreamEventYet: "እስካሁን የስትሪም ክስተት የለም",
    reconnect: "እንደገና ተገናኝ",
    currentCoordinates: "የአሁኑ ኮርዲኔቶች",
    speed: "ፍጥነት",
    destination: "መድረሻ",
    distanceToDestination: "እስከ መድረሻ ርቀት",
    estimatedArrival: "የተገመተ መድረሻ ጊዜ",
    fitRoute: "መንገድ አስተካክል",
    refreshRegistry: "መዝገብ አድስ",
    failedToLoadTrackingRegistry: "የክትትል መዝገብ መጫን አልተሳካም",
    failedToLoadShipmentTracking: "የጭነት ክትትል መጫን አልተሳካም",
    myShipmentTracking: "የእኔ የጭነት ክትትል",
    importerViewSubtitle: "ለመግለጫ እድገት እና ቀጥታ የጭነት እንቅስቃሴ የአስመጪ እይታ",
    searchShipment: "ጭነት ፈልግ",
    searchShipmentHelp: "የመግለጫ ቁጥር፣ የጭነት ማጣቀሻ፣ BL፣ AWB ወይም የኮንቴይነር ቁጥር ይጠቀሙ።",
    searchPlaceholder: "DEC-ET-2026-00001 / SHP-... / BL...",
    searching: "በመፈለግ ላይ...",
    noShipmentSelectedHint: "ምንም ጭነት አልተመረጠም። ታይምላይንና ቀጥታ ካርታ ለመጫን ፍለጋ ያድርጉ።",
    shipmentSummary: "የጭነት ማጠቃለያ",
    declarationNo: "የመግለጫ ቁጥር",
    shipmentRef: "የጭነት ማጣቀሻ",
    coordinates: "ኮርዲኔቶች",
    openFullTracking: "ሙሉ ክትትል ክፈት",
    openPayments: "ክፍያዎችን ክፈት",
    downloadReleaseDocsTitle: "የመልቀቂያ PDF አውርድ",
    completeRequirementsToDownload: "ማውረድ ለማንቃት መስፈርቶቹን ያጠናቅቁ",
    releaseDocsUnavailable: "የመልቀቂያ ሰነዶች አልተዘጋጁም። የጎደለ:",
    paymentConfirmation: "የክፍያ ማረጋገጫ;",
    inspectionReq: "ምርመራ;",
    clearanceReq: "ክሊራንስ;",
    documentsReq: "ሰነዶች",
    statusTimeline: "የሁኔታ ጊዜ መስመር",
    date: "ቀን",
    liveMap: "ቀጥታ ካርታ",
    enterTrackingSearch: "የመግለጫ፣ ክትትል፣ BL ወይም የኮንቴይነር ቁጥር ያስገቡ",
    searchFailed: "ፍለጋ አልተሳካም",
    declarationNotFoundForShipment: "ለዚህ ጭነት መግለጫ አልተገኘም",
    releaseDocsDownloaded: "የመልቀቂያ PDF ወርዷል",
    releaseDocsNotReady: "የመልቀቂያ ሰነዶች ገና አልተዘጋጁም",
    declarationProcessing: "የመግለጫ ሂደት",
    euStyleDeclarationWorkflow: "የEU ዘይቤ የመግለጫ ሂደት ከግምገማ እርምጃዎች ጋር",
    newDeclaration: "አዲስ መግለጫ",
    selectShipmentAndCompleteDeclaration: "ጭነት ይምረጡ እና የጉምሩክ መግለጫ መረጃ ያጠናቅቁ።",
    shipment: "ጭነት",
    selectShipment: "ጭነት ይምረጡ...",
    allShipmentsAlreadyDeclared: "ሁሉም ጭነቶች መግለጫ አላቸው።",
    declarationNumber: "የመግለጫ ቁጥር",
    autoIfEmpty: "ባዶ ከሆነ በራስ-ሰር",
    auto: "በራስ-ሰር",
    declarationDate: "የመግለጫ ቀን",
    declarantAgent: "የአዋጅ ወኪል",
    customsStation: "የጉምሩክ ጣቢያ",
    valuationBasis: "የግምገማ መሰረት",
    currency: "ምንዛሬ",
    tariffRatePercent: "የታሪፍ መጠን (%)",
    selectRate: "መጠን ይምረጡ...",
    custom: "ልዩ",
    customTariffPercent: "ልዩ ታሪፍ (%)",
    dutiesEtb: "ዲውቲ (ETB)",
    optionalManualAmount: "አማራጭ የእጅ መጠን",
    paymentReceiptNumber: "የክፍያ ደረሰኝ ቁጥር",
    estimatedPreview: "የተገመተ ቅድመ እይታ",
    cifValueUsd: "የCIF ዋጋ (USD)",
    exchangeRate: "የምንዛሬ ተመን",
    estimatedDutyEtb: "የተገመተ ዲውቲ (ETB)",
    addShipment: "መግለጫ ጨምር",
    addDeclaration: "መግለጫ ጨምር",
    submitting: "በመላክ ላይ...",
    submitDeclaration: "መግለጫ ላክ",
    declarationsRegistry: "የመግለጫ መዝገብ",
    filterByDeclarationId: "በ declaration_id አጣራ",
    clear: "አጥፋ",
    dateShort: "ቀን",
    tariffPercent: "ታሪፍ %",
    actions: "እርምጃዎች",
    status: "ሁኔታ",
    documents: "ሰነዶች",
    upload: "ጫን",
    approve: "አጽድቅ",
    reject: "አልቀበልም",
    rejectionReasonOptional: "የመከልከል ምክንያት (አማራጭ)",
    noDeclarationRecordsFound: "የመግለጫ መዝገብ አልተገኘም።",
    declarationDocuments: "የመግለጫ ሰነዶች",
    uploadManagedInFileUpload: "የመጫን ሂደት በ File Upload ገጽ ይተዳደራል።",
    goToFileUpload: "ወደ File Upload ሂድ",
    noDocumentsForDeclaration: "ለዚህ መግለጫ ሰነድ የለም።",
    uploaded: "የተጫነ",
    delete: "ሰርዝ",
    deleteThisDocument: "ይህን ሰነድ ልሰርዝ?",
    documentDeleted: "ሰነድ ተሰርዟል",
    deleteFailed: "መሰረዝ አልተሳካም",
    previewing: "ቅድመ እይታ በመያዝ ላይ...",
    previewFailed: "ቅድመ እይታ አልተሳካም",
    ocrPreview: "OCR ቅድመ እይታ",
    pleaseSelectShipment: "እባክዎ ጭነት ይምረጡ።",
    pleaseCompleteRequiredFields: "እባክዎ አስፈላጊ መስኮችን ያጠናቁ።",
    tariffRateRequired: "የታሪፍ መጠን ያስፈልጋል።",
    invalidNumber: "ትክክለኛ ቁጥር ያስገቡ።",
    declarationSubmittedSuccessfully: "መግለጫ በተሳካ ሁኔታ ተልኳል።",
    failedToSubmitDeclaration: "መግለጫ መላክ አልተሳካም",
    failedToLoadDocuments: "ሰነዶችን መጫን አልተሳካም",
    declarationApproved: "መግለጫ ጸድቋል",
    approveFailed: "ማጽደቅ አልተሳካም",
    declarationRejected: "መግለጫ ተከልክሏል",
    rejectFailed: "መከልከል አልተሳካም",
  },
};

const LanguageContext = createContext({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try {
      const saved = localStorage.getItem(KEY);
      if (saved === "am" || saved === "en") return saved;
    } catch {}
    return "en";
  });

  useEffect(() => {
    try {
      localStorage.setItem(KEY, lang);
    } catch {}
    try {
      document.documentElement.setAttribute("lang", lang === "am" ? "am" : "en");
    } catch {}

    // Keep backend user preference in sync so server-side notifications use the same language.
    (async () => {
      try {
        const raw = localStorage.getItem("auth");
        if (!raw) return;
        const parsed = JSON.parse(raw);
        if (!parsed?.token) return;
        const current = String(parsed?.preferred_language || "en").toLowerCase();
        if (current === lang) return;
        const updated = await updateProfileAPI({ preferred_language: lang });
        try { localStorage.setItem("auth", JSON.stringify(updated)); } catch {}
      } catch {}
    })();
  }, [lang]);

  const value = useMemo(() => {
    const bag = STRINGS[lang] || STRINGS.en;
    return {
      lang,
      setLang,
      t: (key) => bag[key] || STRINGS.en[key] || key,
    };
  }, [lang]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
