import React, { useEffect, useState } from "react";
import { SystemHealthAPI } from "../api/systemHealthAPI.js";
import DataTable from "../components/DataTable.jsx";
import MetricCard from "../components/MetricCard.jsx";
import { useToast } from "../context/ToastContext.jsx";

const GROUP_LABELS = {
  importer_customs_registration_no: "Importer customs registration numbers",
  shipment_reference: "Shipment references",
  tracking_reference: "Tracking references",
  clearance_declaration: "Clearances per declaration",
};

const EMPTY = {
  generated_at: null,
  summary: {
    duplicate_groups: 0,
    duplicate_records: 0,
    missing_unique_indexes: 0,
    deprecated_roles: 0,
    blocked_indexes: 0,
    ready_indexes: 0,
  },
  duplicates: {},
  indexes: [],
  index_readiness: [],
  deprecated_roles: [],
  cleanup_plan: {
    mode: "dry-run",
    duplicate_shipments: [],
    duplicate_clearances: [],
  },
  remediation_package: {
    mode: "proposal-only",
    proposed_index_sql: [],
  },
};

function IdList({ values }) {
  return (
    <div className="data-health-id-list">
      {(values || []).map((value) => <code key={value}>{value}</code>)}
    </div>
  );
}

function downloadJson(filename, value) {
  downloadText(filename, "application/json", JSON.stringify(value, null, 2));
}

function downloadText(filename, type, value) {
  const blob = new Blob([value], { type });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function csvEscape(value) {
  const text = String(value ?? "");
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function buildIssueCsv(duplicates) {
  const rows = [["category", "duplicate_value", "duplicate_count", "record_ids"]];
  Object.entries(duplicates || {}).forEach(([category, groups]) => {
    (groups || []).forEach((group) => {
      rows.push([category, group.duplicate_value, group.duplicate_count, (group.record_ids || []).join(" | ")]);
    });
  });
  return rows.map((row) => row.map(csvEscape).join(",")).join("\n");
}

function buildProposedSql(remediationPackage) {
  const lines = [
    "-- PROPOSAL ONLY. This file was generated by Data Health and has not been executed.",
    "-- Review duplicate cleanup evidence, obtain approval, and take a database backup before use.",
    "",
  ];
  (remediationPackage?.proposed_index_sql || []).forEach((item) => {
    lines.push(`-- ${item.index}: ${item.status}; blocker groups: ${item.blocker_groups}`);
    lines.push(item.status === "blocked" ? `-- BLOCKED: ${item.sql}` : item.sql);
    lines.push("");
  });
  return lines.join("\n");
}

export default function DataHealth() {
  const toast = useToast();
  const [data, setData] = useState(EMPTY);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const load = async () => {
    setLoading(true);
    setError("");
    try {
      setData(await SystemHealthAPI.get());
    } catch (e) {
      setError(e.message || "Failed to load data health report");
      toast.error?.(e.message || "Failed to load data health report");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  const duplicateColumns = [
    { key: "duplicate_value", label: "Duplicate value", render: (row) => <code>{row.duplicate_value}</code> },
    { key: "duplicate_count", label: "Records", align: "right" },
    { key: "record_ids", label: "Affected record IDs", render: (row) => <IdList values={row.record_ids} /> },
  ];
  const indexColumns = [
    { key: "index", label: "Unique index", render: (row) => <code>{row.index}</code> },
    {
      key: "exists",
      label: "Status",
      render: (row) => <span className={`data-health-status ${row.exists ? "is-ok" : "is-warning"}`}>{row.exists ? "Present" : "Missing"}</span>,
    },
    { key: "definition", label: "Definition", render: (row) => row.definition ? <code>{row.definition}</code> : "-" },
  ];
  const readinessColumns = [
    { key: "index", label: "Unique index", render: (row) => <code>{row.index}</code> },
    {
      key: "status",
      label: "Readiness",
      render: (row) => <span className={`data-health-status is-${row.status}`}>{row.status}</span>,
    },
    { key: "blocker_groups", label: "Blocker groups", align: "right" },
    { key: "blocker_records", label: "Blocker records", align: "right" },
    { key: "required_action", label: "Required action" },
  ];
  const roleColumns = [
    { key: "role_name", label: "Deprecated role" },
    { key: "role_id", label: "Role ID", render: (row) => <code>{row.role_id}</code> },
    { key: "user_count", label: "Users", align: "right" },
    { key: "audit_count", label: "Audit references", align: "right" },
  ];
  const shipmentPlanColumns = [
    { key: "duplicate_value", label: "Shipment reference", render: (row) => <code>{row.duplicate_value}</code> },
    { key: "recommended_survivor", label: "Recommended survivor", render: (row) => <code>{row.recommended_survivor}</code> },
    { key: "review_and_merge", label: "Review and merge", render: (row) => <IdList values={row.review_and_merge} /> },
    {
      key: "records",
      label: "Dependency evidence",
      render: (row) => (
        <div className="data-health-evidence">
          {(row.records || []).map((record) => (
            <div key={record.shipment_id}>
              <code>{record.shipment_id}</code>
              <span>score {record.dependency_score}; declarations {record.declarations}; documents {record.documents}; tracking {record.tracking_snapshot + record.tracking_points + record.tracking_audits}; transport {record.transport_links + record.transport_events}</span>
            </div>
          ))}
        </div>
      ),
    },
  ];
  const clearancePlanColumns = [
    { key: "declaration_no", label: "Declaration", render: (row) => <div>{row.declaration_no || "-"}<br /><code>{row.declaration_id}</code></div> },
    { key: "recommended_survivor", label: "Recommended survivor", render: (row) => <code>{row.recommended_survivor}</code> },
    { key: "review_before_removal", label: "Review before removal", render: (row) => <IdList values={row.review_before_removal} /> },
    {
      key: "records",
      label: "Completeness evidence",
      render: (row) => (
        <div className="data-health-evidence">
          {(row.records || []).map((record) => (
            <div key={record.clearance_id}>
              <code>{record.clearance_id}</code>
              <span>completeness score {record.completeness_score}; release {record.release_date ? new Date(record.release_date).toLocaleDateString() : "not set"}</span>
            </div>
          ))}
        </div>
      ),
    },
  ];

  return (
    <div className="analytics-page data-health-page">
      <header className="smart-analytics-header">
        <div>
          <h2>Data Health</h2>
          <p>Live integrity diagnostics for duplicates, required unique indexes, and deprecated roles.</p>
        </div>
        <div className="smart-analytics-actions">
          <span className="data-health-generated">
            {data.generated_at ? `Generated ${new Date(data.generated_at).toLocaleString()}` : "Not generated"}
          </span>
          <button type="button" className="btn btn-primary" onClick={load} disabled={loading}>
            {loading ? "Refreshing..." : "Refresh"}
          </button>
          <button
            type="button"
            className="btn"
            onClick={() => downloadJson(`duplicate-cleanup-plan-${new Date().toISOString().slice(0, 10)}.json`, data.cleanup_plan)}
            disabled={loading}
          >
            Download Plan
          </button>
          <button
            type="button"
            className="btn"
            onClick={() => downloadText(`data-health-issues-${new Date().toISOString().slice(0, 10)}.csv`, "text/csv;charset=utf-8", buildIssueCsv(data.duplicates))}
            disabled={loading}
          >
            Download Issues CSV
          </button>
          <button
            type="button"
            className="btn"
            onClick={() => downloadText(`proposed-index-remediation-${new Date().toISOString().slice(0, 10)}.sql`, "text/plain;charset=utf-8", buildProposedSql(data.remediation_package))}
            disabled={loading}
          >
            Download Proposed SQL
          </button>
        </div>
      </header>

      <div className="data-health-notice">
        Diagnostics only. This page does not change or delete records.
      </div>
      {error && <div className="analytics-error">{error}</div>}

      <section className="dashboard-grid dashboard-metrics">
        <MetricCard title="Duplicate groups" value={data.summary?.duplicate_groups || 0} helper="Values used by multiple records" />
        <MetricCard title="Duplicate records" value={data.summary?.duplicate_records || 0} helper="Records inside duplicate groups" />
        <MetricCard title="Missing unique indexes" value={data.summary?.missing_unique_indexes || 0} helper="Protection not yet active" />
        <MetricCard title="Deprecated roles" value={data.summary?.deprecated_roles || 0} helper="Legacy role definitions remaining" />
        <MetricCard title="Blocked indexes" value={data.summary?.blocked_indexes || 0} helper="Duplicates must be reviewed first" />
        <MetricCard title="Ready indexes" value={data.summary?.ready_indexes || 0} helper="Can be activated without cleanup" />
      </section>

      <section className="dashboard-card data-health-table-card">
        <div className="smart-analytics-card-head">
          <h3>Remediation Readiness</h3>
          <span>{data.summary?.blocked_indexes || 0} blocked / {data.summary?.ready_indexes || 0} ready</span>
        </div>
        <div className="smart-analytics-table-wrap">
          <DataTable columns={readinessColumns} rows={data.index_readiness || []} dense emptyText="No readiness diagnostics available" />
        </div>
      </section>

      <section className="dashboard-card data-health-table-card">
        <div className="smart-analytics-card-head">
          <h3>Unique Index Status</h3>
          <span>{data.indexes?.filter((row) => row.exists).length || 0} of {data.indexes?.length || 0} present</span>
        </div>
        <div className="smart-analytics-table-wrap">
          <DataTable columns={indexColumns} rows={data.indexes || []} dense emptyText="No index diagnostics available" />
        </div>
      </section>

      <section className="dashboard-card data-health-table-card data-health-plan">
        <div className="smart-analytics-card-head">
          <h3>Shipment Cleanup Plan</h3>
          <span>Dry run / {data.cleanup_plan?.duplicate_shipments?.length || 0} groups</span>
        </div>
        <p className="data-health-plan-copy">Recommendations favor the shipment with the strongest linked-record evidence. Every non-survivor requires manual merge review.</p>
        <div className="smart-analytics-table-wrap">
          <DataTable columns={shipmentPlanColumns} rows={data.cleanup_plan?.duplicate_shipments || []} dense emptyText="No duplicate shipments require planning" />
        </div>
      </section>

      <section className="dashboard-card data-health-table-card data-health-plan">
        <div className="smart-analytics-card-head">
          <h3>Clearance Cleanup Plan</h3>
          <span>Dry run / {data.cleanup_plan?.duplicate_clearances?.length || 0} groups</span>
        </div>
        <p className="data-health-plan-copy">Recommendations favor the most complete clearance record. Review all alternate records before removal.</p>
        <div className="smart-analytics-table-wrap">
          <DataTable columns={clearancePlanColumns} rows={data.cleanup_plan?.duplicate_clearances || []} dense emptyText="No duplicate clearances require planning" />
        </div>
      </section>

      <section className="data-health-groups">
        {Object.entries(GROUP_LABELS).map(([key, label]) => {
          const rows = data.duplicates?.[key] || [];
          return (
            <div className="dashboard-card data-health-table-card" key={key}>
              <div className="smart-analytics-card-head">
                <h3>{label}</h3>
                <span>{rows.length} duplicate groups</span>
              </div>
              <div className="smart-analytics-table-wrap">
                <DataTable columns={duplicateColumns} rows={rows} dense emptyText="No duplicates found" />
              </div>
            </div>
          );
        })}
      </section>

      <section className="dashboard-card data-health-table-card">
        <div className="smart-analytics-card-head">
          <h3>Deprecated Roles</h3>
          <span>{data.deprecated_roles?.length || 0} roles</span>
        </div>
        <div className="smart-analytics-table-wrap">
          <DataTable columns={roleColumns} rows={data.deprecated_roles || []} dense emptyText="No deprecated roles found" />
        </div>
      </section>
    </div>
  );
}
