-- Reference of feature view creation, mirrors database/views/risk_features.sql
-- Keep this as documentation for the training pipeline.
SELECT declaration_id,
       declaration_no,
       declaration_date,
       declaration_created_at,
       hs_code,
       goods_type,
       description_of_goods,
       quantity,
       unit_of_measure,
       cif_value_usd,
       origin_country,
       destination_port,
       mode_of_transport,
       invoice_value_usd,
       exchange_rate,
       cif_etb,
       duty_paid,
       vat_paid,
       excise_paid,
       total_payable,
       payment_status,
       paid_amount,
       payment_date,
       number_of_queries,
       penalties,
       feedback_score,
       release_date,
       storage_days,
       value_per_unit_usd,
       value_ratio_vs_hs_p50,
       undervaluation_flag,
       overvaluation_flag,
       goods_type_sensitive,
       night_submission,
       duty_density,
       payment_status_flag,
       partial_paid_ratio,
       payment_delay_days,
       hs_prior_risk,
       route_prior_risk,
       origin_watchlist_flag,
       label_risk_event
FROM risk_features;

